#for incomplete documentaion look at https://codeberg.org/sofoxe1/xr_overlay/src/branch/main/examples/cef_overlay/src/bindings_overwrites.toml
[oculus_touch]
oyasumi_overlay_switch=[{path="left/input/x/touch"},{path="left/input/y/touch"},{path="right/input/thumbstick/click"}]
microphone_switch=[{path="left/input/thumbstick/click"},{path="right/input/thumbstick/click"}]
[oculus_touch_pro]
oyasumi_overlay_switch=[{path="left/input/x/touch"},{path="left/input/y/touch"},{path="right/input/thumbstick/click"}]
[pico_4]
oyasumi_overlay_switch=[{path="left/input/x/touch"},{path="left/input/y/touch"},{path="right/input/thumbstick/click"}]
[pico_neo3]
oyasumi_overlay_switch=[{path="left/input/x/touch"},{path="left/input/y/touch"},{path="right/input/thumbstick/click"}]
[valve_index]
oyasumi_overlay_switch=[{path="left/input/a/touch"},{path="left/input/b/touch"},{path="right/input/thumbstick/click"}]
[vive_cosmos]
oyasumi_overlay_switch=[{path="left/input/thumbstick/click"},{path="right/input/thumbstick/click"}]
[vive_focus3]
oyasumi_overlay_switch=[{path="left/input/thumbstick/click"},{path="right/input/thumbstick/click"}]