[pointers]
draw_only_when_on_overlay = true
#alpha is broken
left_color = [1.0, 1.0, 1.0, 0.2]
right_color = [1.0, 1.0, 1.0, 0.2]
overlay_move_speed = 0.01
[main_overlay]
#this set the browser refresh rate
framerate = "/2" #half the runtime framerate
# overlay_fps="*2"
# overlay_fps=30
# ...
position = [0.0, 0.0, -0.4]
resolution = [1024, 1024]
size = [0.6, 0.6]
#posible values are: stage,view,local
reference_space="stage"
#posible values are: last_controller (relative position), hmd (relative position), left_controller (relative position), right_controller (relative controller) keep
show_mode="last_controller"

[notification_overlay]
framerate = "/2"
position = [0.0, -0.3, -0.6]
resolution = [1024, 1024]
size = [0.5, 0.5]
reference_space="view"

[mute_indicator_overlay]
size = [0.04, 0.04]
position = [-0.3, -0.3, -0.6]
reference_space="view"
