use std::{
    fs,
    io::{self, Write},
};

use log::error;

use crate::vr::{
    model::{OVRFrameLimits, VRStatus},
    openxr::{OXR_HANDLE, OXR_STATE},
};

#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Clone, Copy)]
pub enum GameAppId {
    VRChat,
    Resonite,
    ChilloutVR,
}
impl From<u32> for GameAppId {
    fn from(value: u32) -> Self {
        match value {
            438100 => GameAppId::VRChat,
            2519830 => GameAppId::Resonite,
            661130 => GameAppId::ChilloutVR,
            _ => unimplemented!("unknown appid:{}", value),
        }
    }
}

pub async fn get_app_framelimit(app_id: u32) -> Option<OVRFrameLimits> {
    if *OXR_STATE.lock().await != VRStatus::Initialized {
        return None;
    }
    let target_fps = OXR_HANDLE
        .get()
        .unwrap()
        .lock()
        .await
        .current_refresh_rate() as u8;
    let mangohud_conf_name = match GameAppId::from(app_id) {
        GameAppId::VRChat => "wine-VRChat.conf",
        GameAppId::Resonite => "wine-Resonite.conf",
        GameAppId::ChilloutVR => "wine-ChilloutVR.conf",
    };
    if let Some(home) = std::env::home_dir() {
        let mut mangohud_path = home;
        mangohud_path.push(".config");
        mangohud_path.push("MangoHud");
        if !mangohud_path.is_dir() {
            error!(
                "[core] Unabled to get frame rate: Failed to get: {:?}",
                mangohud_path
            );
            return None;
        }

        let mut game_conf_path = mangohud_path.clone();
        game_conf_path.push(mangohud_conf_name);
        if !game_conf_path.is_file() {
            return None;
        }
        for line in fs::read_to_string(game_conf_path).ok()?.lines() {
            if line.starts_with("fps_limit=") {
                match line
                    .chars()
                    .skip("fps_limit=".len())
                    .collect::<String>()
                    .parse::<u8>()
                {
                    Ok(v) => {
                        if v == target_fps {
                            return None;
                        }
                        let ret = (target_fps / v) + 1;
                        return Some(OVRFrameLimits {
                            additional_frames_to_predict: ret,
                            frames_to_throttle: ret,
                        });
                    }
                    Err(_) => {
                        error!(
                            "[core] Unabled to get frame rate: mallformated fps_limit value:'{}'",
                            line
                        );
                        return None;
                    }
                }
            }
        }
    } else {
        error!("[core] Unabled to get frame rate: Failed to get home directory");
        return None;
    };

    // fs::read_to_string()
    None
}
pub async fn limit_frame_rate(
    app_id: u32,
    limits: Option<OVRFrameLimits>,
) -> Result<(), io::Error> {
    if *OXR_STATE.lock().await != VRStatus::Initialized {
        log::debug!("called limit_frame_rate when not read");
        return Ok(());
    }
    let mut target_fps = OXR_HANDLE
        .get()
        .unwrap()
        .lock()
        .await
        .current_refresh_rate() as u8;
    
    if let Some(limits) = &limits {
        //im guesing how it works
        debug_assert_eq!(
            limits.additional_frames_to_predict,
            limits.frames_to_throttle
        );
        target_fps /= limits.additional_frames_to_predict + 1;
    }
    log::info!("setting fps limit for: {} at:{}", app_id, target_fps);
    let mangohud_conf_name = match GameAppId::from(app_id) {
        GameAppId::VRChat => "wine-VRChat.conf",
        GameAppId::Resonite => "wine-Resonite.conf",
        GameAppId::ChilloutVR => "wine-ChilloutVR.conf",
    };
    if let Some(home) = std::env::home_dir() {
        let mut mangohud_path = home;
        mangohud_path.push(".config");
        mangohud_path.push("MangoHud");
        if !mangohud_path.is_dir() {
            error!(
                "[core] Unabled to limit frame rate: Failed to get: {:?}",
                mangohud_path
            );
            return Ok(());
        }

        let mut game_conf_path = mangohud_path.clone();
        game_conf_path.push(mangohud_conf_name);
        if !game_conf_path.is_file() {
            let mut default_conf_path = mangohud_path.clone();
            default_conf_path.push("MangoHud.conf");
            if !default_conf_path.is_file() {
                log::info!("no default generating config");
                let mut file = fs::File::create_new(game_conf_path)?;
                file.write_all(format!(
                    "################### File Generated by OyasumiVR ###################\nfps_limit_method=late\nfps_limit={}\n"
                    ,target_fps).as_bytes())?;
                return Ok(());
            } else {
                log::info!("no game specific mangohud config copying default");
                fs::copy(default_conf_path, game_conf_path.clone())?;
            }
        }
        let mut found = false;
        let mut data = fs::read_to_string(&game_conf_path)?
            .lines()
            .map(|line: &str| {
                if line.starts_with("fps_limit=") {
                    found = true;
                    format!("fps_limit={}\n", target_fps)
                } else {
                    format!("{}\n", line)
                }
            })
            .collect::<String>();
        if !found {
            data.push_str(&format!("fps_limit={}\n", target_fps));
        }
        found = false;

        data.lines().for_each(|line| {
            if line.trim().starts_with("fps_limit_method=") {
                found = true;
            }
        });
        if !found {
            data.push_str("fps_limit_method=late\n");
        }
        fs::write(game_conf_path, data)?;
    } else {
        error!("[core] Unabled to limit frame rate: Failed to get home directory");
    };
    Ok(())
}
