use std::{fs, io::Write};

use log::error;

use crate::vr::{model::{OVRFrameLimits, VRStatus}, openxr::{OXR_HANDLE, OXR_STATE}};

#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Clone, Copy)]
pub enum GameAppId {
    VRChat,
    Resonite,
    ChilloutVR,
}
impl From<u32> for GameAppId {
    fn from(value: u32) -> Self {
        match value {
            438100 => GameAppId::VRChat,
            2519830 => GameAppId::Resonite,
            661130 => GameAppId::ChilloutVR,
            _ => unimplemented!("unknown appid:{}", value),
        }
    }
}

pub async fn get_app_framelimit(app_id: u32) -> Option<OVRFrameLimits> {
    if *OXR_STATE.lock().await!=VRStatus::Initialized{
        return None;
    }
    let target_fps = OXR_HANDLE
        .get()
        .unwrap()
        .lock()
        .await
        .current_refresh_rate() as u8;
    let mangohud_conf_name = match GameAppId::from(app_id) {
        GameAppId::VRChat => "wine-VRChat.conf",
        GameAppId::Resonite => "wine-Resonite.conf",
        GameAppId::ChilloutVR => "wine-ChilloutVR.conf",
    };
    if let Some(home) = std::env::home_dir() {
        let mut mangohud_path = home;
        mangohud_path.push(".config");
        mangohud_path.push("MangoHud");
        if !mangohud_path.is_dir() {
            error!(
                "[core] Unabled to get frame rate: Failed to get: {:?}",
                mangohud_path
            );
            return None;
        }

        let mut game_conf_path = mangohud_path.clone();
        game_conf_path.push(mangohud_conf_name);
        if !game_conf_path.is_file() {
            return None;
        }
        for line in fs::read_to_string(game_conf_path).unwrap().lines() {
            if line.starts_with("fps_limit=") {
                match line
                    .chars()
                    .skip("fps_limit=".len())
                    .collect::<String>()
                    .parse::<u8>()
                {
                    Ok(v) => {
                        if v == target_fps {
                            return None;
                        }
                        let ret = (target_fps / v) + 1;
                        return Some(OVRFrameLimits {
                            additional_frames_to_predict: ret,
                            frames_to_throttle: ret,
                        });
                    }
                    Err(_) => {
                        error!(
                            "[core] Unabled to get frame rate: mallformated fps_limit value:'{}'",
                            line
                        );
                        return None;
                    }
                }
            }
        }
    } else {
        error!("[core] Unabled to get frame rate: Failed to get home directory");
        return None;
    };

    // fs::read_to_string()
    None
}
pub async fn limit_frame_rate(app_id: u32, limits: Option<OVRFrameLimits>) {
      if *OXR_STATE.lock().await!=VRStatus::Initialized{
        log::debug!("called limit_frame_rate when not read");
        return;
    }
    let mut target_fps = OXR_HANDLE
        .get()
        .unwrap()
        .lock()
        .await
        .current_refresh_rate() as u8;
    if let Some(limits) = &limits {
        //im guesing how it works
        debug_assert_eq!(
            limits.additional_frames_to_predict,
            limits.frames_to_throttle
        );
        target_fps /= limits.additional_frames_to_predict + 1;
    }
    let mangohud_conf_name = match GameAppId::from(app_id) {
        GameAppId::VRChat => "wine-VRChat.conf",
        GameAppId::Resonite => "wine-Resonite.conf",
        GameAppId::ChilloutVR => "wine-ChilloutVR.conf",
    };
    if let Some(home) = std::env::home_dir() {
        let mut mangohud_path = home;
        mangohud_path.push(".config");
        mangohud_path.push("MangoHud");
        if !mangohud_path.is_dir() {
            error!(
                "[core] Unabled to limit frame rate: Failed to get: {:?}",
                mangohud_path
            );
            return;
        }

        let mut game_conf_path = mangohud_path.clone();
        game_conf_path.push(mangohud_conf_name);
        if !game_conf_path.is_file() {
            let mut default_conf_path = mangohud_path.clone();
            default_conf_path.push("MangoHud.conf");
            if !default_conf_path.is_file() {
                let mut file = fs::File::create_new(game_conf_path).unwrap();
                file.write_all(format!(
                    "################### File Generated by OyasumiVR ###################\nfps_limit_method=late\nfps_limit={}\n"
                    ,target_fps).as_bytes()).unwrap();
                return;
            } else {
                fs::copy(default_conf_path, game_conf_path.clone()).unwrap();
            }
        }
        let data = fs::read_to_string(&game_conf_path)
            .unwrap()
            .lines()
            .map(|line: &str| {
                if line.starts_with("fps_limit=") {
                    format!("fps_limit={}\n", target_fps)
                } else {
                    format!("{}\n", line)
                }
            })
            .collect::<String>();
        fs::write(game_conf_path, data).unwrap();
    } else {
        error!("[core] Unabled to limit frame rate: Failed to get home directory");
    };
}
